# =================================================
# Configuración para text_extractor.py
# =================================================

github:
  repos:
    - owner: huggingface
      repo: transformers
      path: docs/source/en

    - owner: huggingface
      repo: peft
      path: docs/source

    - owner: huggingface
      repo: accelerate
      path: docs/source

    - owner: huggingface
      repo: blog
      path: /

jsonl_database_path: data/docs_en_2023_06_23.jsonl

# =================================================
# Configuración para ai_conversation.py
# =================================================

recreate_chroma_db: false
embeddings_provider: openai # puede ser "cohere"
embeddings_model: text-embedding-ada-002 # con cohere puede ser "embed-multilingual-v2.0"
chroma_db_name: chroma_docs

chat_model:
  model_name: gpt-3.5-turbo
  temperature: 0.9
  max_tokens: 256

text_splitting:
  chunk_size: 500
  chunk_overlap: 50

document_retrieval:
  k: 5

conversation_chain:
  verbose: false
